name: social_devs_app
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  custom_events:
    path: ../packages/custom_events

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  uno: ^1.0.1+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  asuka: ^2.0.0+1
  web_socket_channel: ^2.2.0
  bubble: ^1.2.1
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  image_picker_web: ^2.1.1
  video_player: ^2.4.5
  video_player_web: ^2.0.12
  pointer_interceptor: ^0.9.3+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true